import {DocumentTextIcon} from '@sanity/icons/DocumentText'
import {defineArrayMember, defineField, defineType} from 'sanity'

export const post = defineType({
  name: 'post',
  title: 'Article',
  type: 'document',
  icon: DocumentTextIcon,
  groups: [
    {name: 'content', title: 'Content', default: true},
    {name: 'meta', title: 'Byline & sections'},
    {name: 'seo', title: 'SEO'},
  ],
  fields: [
    defineField({
      name: 'title',
      title: 'Headline',
      type: 'string',
      group: 'content',
      validation: (rule) => rule.required().max(160),
    }),
    defineField({
      name: 'slug',
      title: 'URL',
      type: 'slug',
      group: 'content',
      description: 'The article lives at /section/url. Changing it after publishing breaks shared links.',
      options: {source: 'title', maxLength: 96},
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'excerpt',
      title: 'Standfirst',
      type: 'text',
      rows: 3,
      group: 'content',
      description: 'One or two sentences under the headline. Also used in previews and search results.',
      validation: (rule) => rule.max(320),
    }),
    defineField({
      name: 'mainImage',
      title: 'Lead image',
      type: 'figure',
      group: 'content',
    }),
    defineField({
      name: 'body',
      title: 'Body',
      type: 'blockContent',
      group: 'content',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'author',
      title: 'Author',
      type: 'reference',
      to: [{type: 'author'}],
      group: 'meta',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'category',
      title: 'Section',
      type: 'reference',
      to: [{type: 'category'}],
      group: 'meta',
      description: 'Main section. It is part of the article address.',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'otherCategories',
      title: 'Also show in',
      type: 'array',
      of: [defineArrayMember({type: 'reference', to: [{type: 'category'}]})],
      group: 'meta',
      validation: (rule) => rule.unique(),
    }),
    defineField({
      name: 'series',
      title: 'Series',
      type: 'reference',
      to: [{type: 'series'}],
      group: 'meta',
    }),
    defineField({
      name: 'publishedAt',
      title: 'Published',
      type: 'datetime',
      group: 'meta',
      initialValue: () => new Date().toISOString(),
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'updatedAt',
      title: 'Updated',
      type: 'datetime',
      group: 'meta',
      description: 'Set only when the article was meaningfully revised. Shown to readers.',
    }),
    defineField({
      name: 'tags',
      title: 'Topics',
      type: 'array',
      of: [defineArrayMember({type: 'string'})],
      group: 'meta',
      options: {layout: 'tags'},
      description: 'Used for related articles and search. Not shown as separate pages.',
    }),
    defineField({
      name: 'allowComments',
      title: 'Allow comments',
      type: 'boolean',
      group: 'meta',
      initialValue: true,
    }),
    defineField({name: 'seo', title: 'SEO', type: 'seo', group: 'seo'}),
    defineField({
      name: 'newsletterSentAt',
      title: 'Emailed to subscribers',
      type: 'datetime',
      group: 'meta',
      readOnly: true,
      description: 'Set automatically when the newsletter about this article goes out.',
    }),
    defineField({
      name: 'legacyUrl',
      title: 'Old WordPress address',
      type: 'string',
      group: 'seo',
      readOnly: true,
      description: 'Filled by the import. Visitors on this address are redirected here.',
    }),
  ],
  orderings: [
    {
      title: 'Newest first',
      name: 'publishedDesc',
      by: [{field: 'publishedAt', direction: 'desc'}],
    },
  ],
  preview: {
    select: {
      title: 'title',
      author: 'author.name',
      section: 'category.title',
      date: 'publishedAt',
      media: 'mainImage',
    },
    prepare: ({title, author, section, date, media}) => ({
      title,
      subtitle: [section, author, date ? new Date(date).toLocaleDateString('en-GB') : 'No date']
        .filter(Boolean)
        .join(' · '),
      media,
    }),
  },
})
