import {CogIcon} from '@sanity/icons/Cog'
import {defineArrayMember, defineField, defineType} from 'sanity'

const menuLink = (name: string, example: string) =>
  defineArrayMember({
    type: 'object',
    name,
    fields: [
      {name: 'label', title: 'Назва', type: 'string', validation: (rule) => rule.required()},
      {
        name: 'href',
        title: 'Шлях',
        type: 'string',
        description: `Наприклад ${example}`,
        validation: (rule) => rule.required(),
      },
    ],
    preview: {select: {title: 'label', subtitle: 'href'}},
  })

export const siteSettings = defineType({
  name: 'siteSettings',
  title: 'Налаштування сайту',
  type: 'document',
  icon: CogIcon,
  groups: [
    {name: 'brand', title: 'Видання', default: true},
    {name: 'navigation', title: 'Меню'},
    {name: 'newsletter', title: 'Розсилка'},
    {name: 'tracking', title: 'Аналітика'},
  ],
  fields: [
    defineField({
      name: 'title',
      title: 'Назва видання',
      type: 'string',
      group: 'brand',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'tagline',
      title: 'Слоган',
      type: 'string',
      group: 'brand',
      description: 'Під логотипом. Наприклад: Signals of What’s Next',
    }),
    defineField({
      name: 'description',
      title: 'Опис',
      type: 'text',
      rows: 3,
      group: 'brand',
      description: 'Для Google і соцмереж (головна сторінка).',
    }),
    defineField({
      name: 'logo',
      title: 'Логотип',
      type: 'image',
      group: 'brand',
      description: 'Темний логотип на прозорому фоні. У нічному режимі сайт сам робить його світлим.',
    }),
    defineField({
      name: 'ogImage',
      title: 'Зображення для соцмереж (за замовчуванням)',
      type: 'image',
      group: 'brand',
    }),
    defineField({
      name: 'contactEmail',
      title: 'Email редакції',
      type: 'string',
      group: 'brand',
      description: 'Сюди надходять листи з форм Contacts і Contribute.',
      validation: (rule) => rule.email(),
    }),
    defineField({
      name: 'social',
      title: 'Соцмережі видання',
      type: 'array',
      group: 'brand',
      of: [defineArrayMember({type: 'socialLink'})],
    }),
    defineField({
      name: 'footerNote',
      title: 'Текст у футері',
      type: 'text',
      rows: 3,
      group: 'brand',
      description: 'Порожньо — показується опис.',
    }),
    defineField({
      name: 'mainMenu',
      title: 'Головне меню',
      type: 'array',
      group: 'navigation',
      description: 'Розділи під логотипом (Home додається сам). Перетягуйте, щоб змінити порядок.',
      of: [defineArrayMember({type: 'reference', to: [{type: 'category'}, {type: 'page'}]})],
      validation: (rule) => rule.unique(),
    }),
    defineField({
      name: 'topMenu',
      title: 'Верхнє меню',
      type: 'array',
      group: 'navigation',
      description: 'Невеликі посилання у верхньому рядку і в мобільному меню.',
      of: [menuLink('menuLink', '/authors або /about')],
    }),
    defineField({
      name: 'footerMenu',
      title: 'Меню у футері',
      type: 'array',
      group: 'navigation',
      description: 'Посилання у футері поруч із розділами. Перетягуйте, щоб змінити порядок.',
      of: [menuLink('footerLink', '/contribute або /privacy-policy')],
    }),
    defineField({
      name: 'newsletterTitle',
      title: 'Заголовок підписки',
      type: 'string',
      group: 'newsletter',
      description: 'У формах підписки на сайті.',
      initialValue: 'Discover more from Cambridge Radar - Signals of What’s Next',
    }),
    defineField({
      name: 'newsletterText',
      title: 'Текст підписки',
      type: 'text',
      rows: 2,
      group: 'newsletter',
      initialValue: 'Subscribe to get the latest posts sent to your email.',
    }),
    defineField({
      name: 'newsletterAutoSend',
      title: 'Надсилати підписникам кожну нову статтю',
      type: 'boolean',
      group: 'newsletter',
      description: 'Лист іде один раз, у момент першої публікації статті.',
      initialValue: true,
    }),
    defineField({
      name: 'gaId',
      title: 'Google Analytics 4 — ID',
      type: 'string',
      group: 'tracking',
      description: 'Починається з G-. Вмикається лише після згоди читача на cookies.',
      validation: (rule) => rule.regex(/^G-[A-Z0-9]+$/, {name: 'GA4 ID'}),
    }),
    defineField({
      name: 'clarityId',
      title: 'Microsoft Clarity — ID проєкту',
      type: 'string',
      group: 'tracking',
      description: 'Вмикається лише після згоди читача на cookies.',
    }),
    defineField({
      name: 'gtmId',
      title: 'Google Tag Manager — ID контейнера',
      type: 'string',
      group: 'tracking',
      description: 'Необовʼязково, починається з GTM-. Для рекламних тегів (LinkedIn, Meta) без змін у коді. Лише після згоди.',
      validation: (rule) => rule.regex(/^GTM-[A-Z0-9]+$/, {name: 'GTM ID'}),
    }),
    defineField({
      name: 'googleVerification',
      title: 'Google Search Console — код підтвердження',
      type: 'string',
      group: 'tracking',
      description: 'Значення мета-тегу google-site-verification.',
    }),
    defineField({
      name: 'bingVerification',
      title: 'Bing Webmaster — код підтвердження',
      type: 'string',
      group: 'tracking',
      description: 'Значення мета-тегу msvalidate.01.',
    }),
  ],
  preview: {prepare: () => ({title: 'Налаштування сайту'})},
})
