import {CogIcon} from '@sanity/icons'
import {defineArrayMember, defineField, defineType} from 'sanity'

export const siteSettings = defineType({
  name: 'siteSettings',
  title: 'Site settings',
  type: 'document',
  icon: CogIcon,
  groups: [
    {name: 'brand', title: 'Brand', default: true},
    {name: 'navigation', title: 'Menus'},
    {name: 'newsletter', title: 'Newsletter'},
    {name: 'tracking', title: 'Analytics'},
  ],
  fields: [
    defineField({
      name: 'title',
      title: 'Publication name',
      type: 'string',
      group: 'brand',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'tagline',
      title: 'Tagline',
      type: 'string',
      group: 'brand',
      description: 'For example: Signals of What’s Next',
    }),
    defineField({
      name: 'description',
      title: 'Description',
      type: 'text',
      rows: 3,
      group: 'brand',
      description: 'Used by Google and social networks for the home page.',
    }),
    defineField({
      name: 'logo',
      title: 'Logo',
      type: 'image',
      group: 'brand',
      description: 'Dark logo on transparent background. The site inverts it for night mode.',
    }),
    defineField({
      name: 'ogImage',
      title: 'Default social share image',
      type: 'image',
      group: 'brand',
    }),
    defineField({
      name: 'contactEmail',
      title: 'Editorial email',
      type: 'string',
      group: 'brand',
      description: 'Contact form messages and new comments are sent here.',
      validation: (rule) => rule.email(),
    }),
    defineField({
      name: 'social',
      title: 'Social profiles',
      type: 'array',
      group: 'brand',
      of: [defineArrayMember({type: 'socialLink'})],
    }),
    defineField({
      name: 'footerNote',
      title: 'Footer note',
      type: 'text',
      rows: 3,
      group: 'brand',
    }),
    defineField({
      name: 'mainMenu',
      title: 'Main menu',
      type: 'array',
      group: 'navigation',
      description: 'Sections under the logo. Drag to reorder.',
      of: [defineArrayMember({type: 'reference', to: [{type: 'category'}, {type: 'page'}]})],
      validation: (rule) => rule.unique(),
    }),
    defineField({
      name: 'topMenu',
      title: 'Top bar menu',
      type: 'array',
      group: 'navigation',
      description: 'Small links in the top bar: About, Authors, Contacts.',
      of: [
        defineArrayMember({
          type: 'object',
          name: 'menuLink',
          fields: [
            {name: 'label', title: 'Label', type: 'string', validation: (rule) => rule.required()},
            {
              name: 'href',
              title: 'Path',
              type: 'string',
              description: 'For example /authors or /about',
              validation: (rule) => rule.required(),
            },
          ],
          preview: {select: {title: 'label', subtitle: 'href'}},
        }),
      ],
    }),
    defineField({
      name: 'newsletterTitle',
      title: 'Sign-up heading',
      type: 'string',
      group: 'newsletter',
      initialValue: 'Get the Radar in your inbox',
    }),
    defineField({
      name: 'newsletterText',
      title: 'Sign-up text',
      type: 'text',
      rows: 2,
      group: 'newsletter',
      initialValue: 'New analysis from Cambridge Radar, straight to your email. No noise.',
    }),
    defineField({
      name: 'newsletterAutoSend',
      title: 'Email subscribers about each new article',
      type: 'boolean',
      group: 'newsletter',
      initialValue: true,
    }),
    defineField({
      name: 'gaId',
      title: 'Google Analytics 4 ID',
      type: 'string',
      group: 'tracking',
      description: 'Starts with G-. Loads only after the reader accepts cookies.',
      validation: (rule) => rule.regex(/^G-[A-Z0-9]+$/, {name: 'GA4 ID'}),
    }),
    defineField({
      name: 'clarityId',
      title: 'Microsoft Clarity project ID',
      type: 'string',
      group: 'tracking',
      description: 'Loads only after the reader accepts cookies.',
    }),
    defineField({
      name: 'gtmId',
      title: 'Google Tag Manager container ID',
      type: 'string',
      group: 'tracking',
      description: 'Optional, starts with GTM-. For marketing tags (LinkedIn, Meta) added without a deploy. Loads only after consent.',
      validation: (rule) => rule.regex(/^GTM-[A-Z0-9]+$/, {name: 'GTM ID'}),
    }),
    defineField({
      name: 'googleVerification',
      title: 'Google Search Console verification code',
      type: 'string',
      group: 'tracking',
      description: 'The content of the google-site-verification meta tag.',
    }),
    defineField({
      name: 'bingVerification',
      title: 'Bing Webmaster verification code',
      type: 'string',
      group: 'tracking',
      description: 'The content of the msvalidate.01 meta tag.',
    }),
  ],
  preview: {prepare: () => ({title: 'Site settings'})},
})
